server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672